// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Image20;
extern lv_obj_t * ui_Image13;
extern lv_obj_t * ui_Image14;
extern lv_obj_t * ui_Image15;
extern lv_obj_t * ui_Image16;
extern lv_obj_t * ui_Image17;
extern lv_obj_t * ui_Image18;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(
    ui_img_orange_white_bold_coffee_and_toast_logo_png);    // assets/Orange White Bold Coffee and Toast Logo.png
LV_IMG_DECLARE(ui_img_square_png);    // assets/square.png
LV_IMG_DECLARE(ui_img_77997250);    // assets/toast1-removebg-preview.png
LV_IMG_DECLARE(ui_img_1819508605);    // assets/toast2-removebg-preview.png
LV_IMG_DECLARE(ui_img_1475470140);    // assets/toast3-removebg-preview.png
LV_IMG_DECLARE(ui_img_1709373061);    // assets/toast4-removebg-preview.png
LV_IMG_DECLARE(ui_img_1135424454);    // assets/toast5-removebg-preview.png
LV_IMG_DECLARE(ui_img_762081401);    // assets/toast6-removebg-preview.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
