// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image1, &ui_img_orange_white_bold_coffee_and_toast_logo_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 73
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 61
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image20 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image20, &ui_img_square_png);
    lv_obj_set_width(ui_Image20, LV_SIZE_CONTENT);   /// 54
    lv_obj_set_height(ui_Image20, LV_SIZE_CONTENT);    /// 54
    lv_obj_set_x(ui_Image20, -1);
    lv_obj_set_y(ui_Image20, -88);
    lv_obj_set_align(ui_Image20, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image20, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image13 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image13, &ui_img_77997250);
    lv_obj_set_width(ui_Image13, LV_SIZE_CONTENT);   /// 49
    lv_obj_set_height(ui_Image13, LV_SIZE_CONTENT);    /// 49
    lv_obj_set_x(ui_Image13, -1);
    lv_obj_set_y(ui_Image13, -91);
    lv_obj_set_align(ui_Image13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image13, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image14 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image14, &ui_img_1819508605);
    lv_obj_set_width(ui_Image14, LV_SIZE_CONTENT);   /// 51
    lv_obj_set_height(ui_Image14, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_Image14, 72);
    lv_obj_set_y(ui_Image14, -45);
    lv_obj_set_align(ui_Image14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image14, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image15 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image15, &ui_img_1475470140);
    lv_obj_set_width(ui_Image15, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_Image15, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_Image15, 77);
    lv_obj_set_y(ui_Image15, 44);
    lv_obj_set_align(ui_Image15, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image15, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image16 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image16, &ui_img_1709373061);
    lv_obj_set_width(ui_Image16, LV_SIZE_CONTENT);   /// 44
    lv_obj_set_height(ui_Image16, LV_SIZE_CONTENT);    /// 45
    lv_obj_set_x(ui_Image16, 2);
    lv_obj_set_y(ui_Image16, 80);
    lv_obj_set_align(ui_Image16, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image16, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image17 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image17, &ui_img_1135424454);
    lv_obj_set_width(ui_Image17, LV_SIZE_CONTENT);   /// 43
    lv_obj_set_height(ui_Image17, LV_SIZE_CONTENT);    /// 46
    lv_obj_set_x(ui_Image17, -73);
    lv_obj_set_y(ui_Image17, 41);
    lv_obj_set_align(ui_Image17, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image17, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image18 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image18, &ui_img_762081401);
    lv_obj_set_width(ui_Image18, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_Image18, LV_SIZE_CONTENT);    /// 45
    lv_obj_set_x(ui_Image18, -75);
    lv_obj_set_y(ui_Image18, -45);
    lv_obj_set_align(ui_Image18, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image18, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}
